/**
 * The parser client's failure taxonomy.
 *
 * The happy path is one test. The rest are the cases that decide whether a user sees "this looks
 * like a scan", "something went wrong, try again", or a spinner forever — and those three are only
 * distinguishable if this file keeps them distinguishable.
 *
 * The golden fixtures are reused deliberately: they are generated by the Python service
 * (`ai/resume-parser/tests/test_contract.py`), so these tests exercise real response bodies rather
 * than shapes invented here to match the code.
 */

import { readFileSync } from 'node:fs';
import { fileURLToPath } from 'node:url';
import { join } from 'node:path';
import { describe, expect, it, vi } from 'vitest';
import type { ParseRequestWire } from '@zentavio/types';
import { ParserClient } from './parser-client.ts';

const FIXTURE_DIR = fileURLToPath(new URL('../../../../tests/fixtures/resume-parser/', import.meta.url));

function fixture(name: string): { httpStatus: number; body: unknown } {
  return JSON.parse(readFileSync(join(FIXTURE_DIR, `${name}.json`), 'utf8')) as {
    httpStatus: number;
    body: unknown;
  };
}

const REQUEST: ParseRequestWire = {
  document_base64: 'U2tpbGxzCkt1YmVybmV0ZXM=',
  content_type: 'text/plain',
  skills: [{ slug: 'kubernetes', name: 'Kubernetes', kind: 'technology', aliases: ['k8s'] }],
};

function respondWith(status: number, body: unknown): typeof fetch {
  return vi.fn(async () =>
    new Response(JSON.stringify(body), {
      status,
      headers: { 'content-type': 'application/json' },
    }),
  ) as unknown as typeof fetch;
}

function client(fetchImpl: typeof fetch, baseUrl = 'http://parser.internal'): ParserClient {
  return new ParserClient({ baseUrl, fetchImpl });
}

describe('successful parses', () => {
  it('returns the validated response for a clean parse', async () => {
    const { body } = fixture('ok');
    const outcome = await client(respondWith(200, body)).parse(REQUEST);

    expect(outcome.kind).toBe('parsed');
    if (outcome.kind !== 'parsed') return;
    expect(outcome.response.status).toBe('ok');
    expect(outcome.response.parser_version).toBeTruthy();
  });

  it('treats an unreadable résumé as a result, not a failure', async () => {
    // The distinction the whole taxonomy exists for. `unknown` arrives as HTTP 200 and must reach
    // the user as an explanation, not as a retry or an error page.
    const { body } = fixture('unknown-scan');
    const outcome = await client(respondWith(200, body)).parse(REQUEST);

    expect(outcome.kind).toBe('parsed');
    if (outcome.kind !== 'parsed') return;
    expect(outcome.response.status).toBe('unknown');
    expect(outcome.response.reason).toBeTruthy();
  });

  it('passes a partial result through with its caveat intact', async () => {
    const { body } = fixture('partial-nothing-recognised');
    const outcome = await client(respondWith(200, body)).parse(REQUEST);

    expect(outcome.kind).toBe('parsed');
    if (outcome.kind !== 'parsed') return;
    expect(outcome.response.status).toBe('partial');
    expect(outcome.response.reason).toBeTruthy();
  });
});

describe('rejections', () => {
  it('surfaces the parser refusing the request, with its correlation id', async () => {
    const { httpStatus, body } = fixture('error-unsupported-type');
    const outcome = await client(respondWith(httpStatus, body)).parse(REQUEST);

    expect(outcome.kind).toBe('rejected');
    if (outcome.kind !== 'rejected') return;
    expect(outcome.code).toBe('VALIDATION_FAILED');
    // Without this, a user report cannot be tied to a log line — which is the only reason the field
    // exists.
    expect(outcome.correlationId).toBeTruthy();
  });
});

describe('unavailability — the only retryable case', () => {
  it('reports an unreachable service without describing the document', async () => {
    const failing = vi.fn(async () => {
      throw new Error('ECONNREFUSED 10.0.0.5:8000');
    }) as unknown as typeof fetch;

    const outcome = await client(failing).parse(REQUEST);
    expect(outcome).toEqual({ kind: 'unavailable', reason: 'unreachable', retryable: true });
  });

  it('reports a timeout distinctly from an unreachable service', async () => {
    const aborting = vi.fn(async () => {
      const error = new Error('aborted');
      error.name = 'AbortError';
      throw error;
    }) as unknown as typeof fetch;

    const outcome = await client(aborting).parse(REQUEST);
    expect(outcome.kind).toBe('unavailable');
    if (outcome.kind !== 'unavailable') return;
    expect(outcome.reason).toBe('timed out');
  });

  it('refuses a 200 that is not JSON rather than inventing a profile', async () => {
    // A proxy error page served as 200 is the realistic case. Treating it as a parse result would
    // fabricate a profile out of an HTML error.
    const html = vi.fn(async () => new Response('<html>502</html>', { status: 200 })) as unknown as typeof fetch;

    const outcome = await client(html).parse(REQUEST);
    expect(outcome.kind).toBe('unavailable');
    if (outcome.kind !== 'unavailable') return;
    expect(outcome.reason).toBe('malformed response');
  });

  it('refuses a 200 whose shape does not match the contract', async () => {
    // A deploy mismatch: the parser answered, but with a shape this gateway does not understand.
    // Storing it would mean writing a profile with fields silently undefined.
    const wrong = respondWith(200, { status: 'ok', skills: 'not an array' });
    const outcome = await client(wrong).parse(REQUEST);

    expect(outcome.kind).toBe('unavailable');
    if (outcome.kind !== 'unavailable') return;
    expect(outcome.reason).toBe('response did not match the contract');
  });

  it('treats a non-envelope error status as infrastructure', async () => {
    const outcome = await client(respondWith(503, { message: 'service unavailable' })).parse(REQUEST);
    expect(outcome.kind).toBe('unavailable');
    if (outcome.kind !== 'unavailable') return;
    expect(outcome.reason).toContain('503');
  });
});

describe('request construction', () => {
  it('normalises a trailing slash on the base URL', async () => {
    // `${base}/parse` with a trailing slash yields `//parse`, which some proxies redirect and
    // others 404 — a failure that looks like the parser being down.
    const spy = respondWith(200, fixture('ok').body);
    await client(spy, 'http://parser.internal/').parse(REQUEST);

    const [url] = (spy as unknown as ReturnType<typeof vi.fn>).mock.calls[0] as [string];
    expect(url).toBe('http://parser.internal/parse');
  });

  it('sends the closed set with the document', async () => {
    const spy = respondWith(200, fixture('ok').body);
    await client(spy).parse(REQUEST);

    const [, init] = (spy as unknown as ReturnType<typeof vi.fn>).mock.calls[0] as [
      string,
      RequestInit,
    ];
    const sent = JSON.parse(init.body as string) as ParseRequestWire;
    expect(sent.skills).toHaveLength(1);
    expect(sent.content_type).toBe('text/plain');
  });
});
